services:
  - type: web
    name: sribhavani-vasavi-bhavan-pms
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: sribhavani_vasavi_pms
